name: example_eriell
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.55.1
  flutter_bloc: ^8.1.1
  freezed: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.1.0  
  flutter_native_splash: ^2.2.7
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  background_image: assets/images/eriell_splash.png
  android: true
  ios: true
  # image: assets/images/splash.png
  web: false